management:
  endpoints:
    web:
      exposure:
        include: "*"
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    filter-method: webflux
    url: /[.]*
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds
    - bandwidths:
      - capacity: 10
        time: 10
        unit: seconds
        