management:
  security:
    enabled: false
spring:
  cache:
    jcache:
      config: classpath:hazelcast.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: /*
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds