management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: myservice
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    filter-method: zuul
    url: /myservice
    filter-order: -10000
    rate-limits:
    - filter-key-type: ip
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 10
        time: 1
        unit: minutes
zuul:
  routes:
    myservice:
      url: http://localhost:8090
    