management:
  security:
    enabled: false
spring:
  application:
    name: myservice
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  rate-limit:
    enabled: true
    configs:
    - cache-name: buckets
      filter-method: zuul
      filter-key-type: default
      url: /
      filter-order: -10000
      bandwidths: 
      -
        capacity: 20
        time: 1
        unit: minutes               
zuul:
  routes:
    myservice:
      url: http://localhost:8090
    