management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    enabled: true
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets   
    filter-method: servlet
    filter-order: 1
    url: /*
    metricTags:
    - key: IP
      expression: getRemoteAddr()
    - key: USERNAME
      expression: "@securityService.username() != null ? @securityService.username() : 'anonym'"
    - key: URL
      expression: request.getRequestURI()  
    rate-limits:
    - filter-key-type: expression
      execute-condition:  "@securityService.username() == 'admin'"
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 30
        time: 1
        unit: minutes
    - filter-key-type: expression
      execute-condition: "@securityService.username() != 'admin'"
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 30
        time: 10
        unit: minutes