management:
  security:
    enabled: false
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets   
    filter-method: servlet 
    url: /*
    rate-limits:
    - filter-key-type: expression
      execute-condition:  "@securityService.username() == 'admin'"
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 10
        time: 1
        unit: minutes
    - filter-key-type: expression
      execute-condition: "@securityService.username() != 'admin'"
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 15
        time: 10
        unit: minutes